const API='/api';let token=localStorage.getItem('si_token'),plans=[],selectedPlan=null,currentPage='dashboard';const $=id=>document.getElementById(id);const money=n=>'PKR '+Number(n||0).toLocaleString('en-PK',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opt={}){const h={'Content-Type':'application/json',...(opt.headers||{})};if(token)h.Authorization='Bearer '+token;const r=await fetch(API+path,{...opt,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function switchAuth(x){$('loginForm').classList.toggle('hidden',x!=='login');$('signupForm').classList.toggle('hidden',x!=='signup');$('loginTab').classList.toggle('active',x==='login');$('signupTab').classList.toggle('active',x==='signup');$('authMsg').classList.add('hidden')}
function msg(t){$('authMsg').textContent=t;$('authMsg').classList.remove('hidden')}
function togglePassword(id,b){const x=$(id);x.type=x.type==='password'?'text':'password';b.textContent=x.type==='password'?'Show':'Hide'}
async function signup(){const username=$('signupUser').value.trim(),password=$('signupPass').value,confirm=$('signupConfirm').value,referralCode=$('signupReferral').value.trim();if(username.length<3)return msg('Username must be at least 3 characters.');if(password.length<6)return msg('Password must be at least 6 characters.');if(password!==confirm)return msg('Passwords do not match.');try{const r=await api('/auth/signup',{method:'POST',body:JSON.stringify({username,password,referralCode})});token=r.token;localStorage.setItem('si_token',token);startApp()}catch(e){msg(e.message)}}
async function login(){try{const r=await api('/auth/login',{method:'POST',body:JSON.stringify({username:$('loginUser').value.trim(),password:$('loginPass').value})});token=r.token;localStorage.setItem('si_token',token);startApp()}catch(e){msg(e.message)}}
function logout(){token=null;localStorage.removeItem('si_token');$('appView').classList.add('hidden');$('authView').classList.remove('hidden');switchAuth('login')}
function startApp(){$('authView').classList.add('hidden');$('appView').classList.remove('hidden');openPage('dashboard')}
function toggleDrawer(){$('drawer').classList.toggle('hidden')}
function openPage(p){currentPage=p;toggleDrawer();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));renderPage(p)}
async function renderPage(p){const c=$('content');c.innerHTML='<div class="panel">Loading…</div>';try{if(p==='dashboard')return renderDashboard();if(p==='plans')return renderPlans();if(p==='buy')return renderBuy();if(p==='payment')return renderPayment();if(p==='pending')return renderPending();if(p==='investments')return renderInvestments();if(p==='withdrawal')return renderWithdrawal();if(p==='profile')return renderProfile();if(p==='history')return renderHistory();if(p==='notifications')return renderNotifications()}catch(e){if(/Authentication|expired|Invalid/i.test(e.message)){logout();return}c.innerHTML=`<div class="panel">${esc(e.message)}</div>`}}
async function getData(){const [profile,inv]=await Promise.all([api('/profile'),api('/investments')]);return {profile,inv}}
async function renderDashboard(){const {profile,inv}=await getData();const active=inv.filter(x=>x.status==='active').length,total=inv.reduce((s,x)=>s+Number(x.amount),0);$('content').innerHTML=`<div class="hero"><h1>Hi, ${esc(profile.username)} 👋</h1><p>Welcome to your member dashboard</p></div><div class="balance-card"><div><span>Account Balance</span><strong>${money(profile.balance)}</strong></div><div class="wallet">▣</div></div><div class="section-title">Overview</div><div class="grid"><div class="stat"><small>Active Plans</small><b>${active}</b></div><div class="stat"><small>Total Invested</small><b>${money(total)}</b></div><div class="stat"><small>Referral Earnings</small><b>${money(profile.referral_earnings)}</b></div><div class="stat"><small>Account Status</small><b>Active</b></div></div><div class="section-title">Quick actions</div><div class="cards"><button class="action" onclick="openPage('plans')"><span class="ico">◈</span><b>Browse Plans</b><small class="muted">Review available plans</small></button><button class="action" onclick="openPage('withdrawal')"><span class="ico">↗</span><b>Withdrawal</b><small class="muted">Submit a withdrawal request</small></button></div><div class="section-title">Referral</div><div class="ref"><span><small>Your referral code</small><br><b>${esc(profile.referral_code)}</b></span><button class="copy" onclick="copyText('${esc(profile.referral_code)}')">Copy</button></div><p class="footer-note">Investment products and returns, if offered, are subject to the platform's published terms and applicable requirements.</p>`}
async function loadPlans(){plans=await api('/plans')}
async function renderPlans(){await loadPlans();$('content').innerHTML=`<div class="page-title"><div><h2>Investment Plans</h2><div class="muted">Choose from currently available plans</div></div></div><div class="panel">${plans.map((p,i)=>`<div class="plan"><div class="plan-icon">${i+1}</div><div class="plan-main"><b>${esc(p.name)}</b><small>${money(p.amount)} • ${p.duration_days} days • Published rate ${Number(p.daily_rate)}%</small></div><button class="outline" onclick="selectPlan(${p.id})">View</button></div>`).join('')}</div>`}
function selectPlan(id){selectedPlan=plans.find(p=>Number(p.id)===Number(id));openPage('buy')}
function renderBuy(){if(!selectedPlan)return openPage('plans');$('content').innerHTML=`<div class="page-title"><button class="back" onclick="openPage('plans')">‹</button><div><h2>${esc(selectedPlan.name)}</h2><div class="muted">Plan details</div></div></div><div class="panel"><div class="balance-card" style="margin:0"><div><span>Plan amount</span><strong>${money(selectedPlan.amount)}</strong></div><div class="wallet">${selectedPlan.id}</div></div><div class="section-title">Details</div><div class="grid"><div class="stat"><small>Amount</small><b>${money(selectedPlan.amount)}</b></div><div class="stat"><small>Duration</small><b>${selectedPlan.duration_days} Days</b></div><div class="stat"><small>Published rate</small><b>${selectedPlan.daily_rate}%</b></div><div class="stat"><small>Status</small><b>Available</b></div></div><div class="notice" style="margin-top:16px">The displayed rate is informational and is not a promise of profit or a guaranteed return.</div><button class="btn primary full" onclick="openPage('payment')">Continue to payment →</button></div>`}
function renderPayment(){if(!selectedPlan)return openPage('plans');$('content').innerHTML=`<div class="page-title"><button class="back" onclick="openPage('buy')">‹</button><div><h2>Payment</h2><div class="muted">Submit payment evidence for review</div></div></div><div class="panel"><div class="payment"><div class="pay-box"><small>Payment method</small><b>Easypaisa</b></div><div class="pay-box"><small>Account holder</small><b>Muhammad Rizwan</b></div><div class="pay-box"><small>Payment number</small><b>03246442557</b><button class="copy" onclick="copyText('03246442557')">Copy number</button></div><div class="pay-box"><small>Selected plan</small><b>${esc(selectedPlan.name)} · ${money(selectedPlan.amount)}</b></div></div><div class="section-title">Transaction ID</div><input id="tx" class="field" placeholder="Enter transaction ID"><div class="section-title">Payment screenshot <em style="font-weight:400;color:#777">optional</em></div><div class="upload">Upload a clear payment screenshot if available.<input id="shot" type="file" accept="image/*"></div><button class="btn primary full" onclick="submitPayment()">Submit for admin review</button></div>`}
async function submitPayment(){const tx=$('tx').value.trim(),file=$('shot').files[0];if(!tx&&!file)return alert('Provide a transaction ID, a screenshot, or both.');const fd=new FormData();fd.append('planId',selectedPlan.id);if(tx)fd.append('transactionId',tx);if(file)fd.append('paymentScreenshot',file);try{const r=await fetch(API+'/payments',{method:'POST',headers:{Authorization:'Bearer '+token},body:fd});const d=await r.json();if(!r.ok)throw Error(d.error);window.lastTx=tx||'Screenshot attached';openPage('pending')}catch(e){alert(e.message)}}
function renderPending(){$('content').innerHTML=`<div class="panel" style="text-align:center;padding:45px 22px"><div class="avatar" style="margin:auto;font-size:30px">✓</div><h2>Request submitted</h2><p class="muted">Your payment evidence is now pending admin review.</p><div class="pay-box"><small>Reference</small><b>${esc(window.lastTx||'Submitted')}</b></div><button class="btn primary full" onclick="openPage('dashboard')">Back to dashboard</button></div>`}
async function renderInvestments(){const a=await api('/investments');$('content').innerHTML=`<div class="page-title"><div><h2>My Plans</h2><div class="muted">Your approved investment records</div></div></div><div class="panel">${a.length?a.map(x=>`<div class="list-item"><div class="row"><b>${esc(x.plan_name)}</b><span class="status ${x.status}">${esc(x.status)}</span></div><div class="row"><small>Amount</small><b>${money(x.amount)}</b></div><div class="row"><small>Start</small><small>${new Date(x.start_at).toLocaleString()}</small></div><div class="row"><small>End</small><small>${new Date(x.end_at).toLocaleString()}</small></div></div>`).join(''):'<p class="muted">No approved plans yet.</p>'}</div>`}
async function renderWithdrawal(){const p=await api('/profile');$('content').innerHTML=`<div class="page-title"><div><h2>Withdrawal</h2><div class="muted">Submit a request to the admin team</div></div></div><div class="panel"><div class="balance-card" style="margin:0"><div><span>Available account balance</span><strong>${money(p.balance)}</strong></div><div class="wallet">↗</div></div><label class="section-title">Amount</label><input id="wdAmount" class="field" type="number" min="1" placeholder="Enter amount"><label class="section-title">Payment method</label><select id="wdMethod" class="field" onchange="withdrawFields()"><option>Easypaisa</option><option>JazzCash</option><option>Bank Account</option></select><div id="wdFields"></div><button class="btn primary full" onclick="requestWithdrawal()">Submit withdrawal</button><p id="wdMsg" class="muted"></p></div>`;withdrawFields()}
function withdrawFields(){const m=$('wdMethod').value;if(m==='Easypaisa')$('wdFields').innerHTML='<label class="section-title">Easypaisa number</label><input id="wdAccount" class="field" placeholder="03XXXXXXXXX">';else if(m==='JazzCash')$('wdFields').innerHTML='<label class="section-title">JazzCash number</label><input id="wdAccount" class="field" placeholder="03XXXXXXXXX">';else $('wdFields').innerHTML='<label class="section-title">Bank name</label><select id="wdBank" class="field"><option>HBL</option><option>UBL</option><option>MCB Bank</option><option>Meezan Bank</option><option>Allied Bank</option><option>Bank Alfalah</option><option>Bank Al Habib</option><option>Askari Bank</option><option>Faysal Bank</option><option>Standard Chartered Pakistan</option><option>National Bank of Pakistan</option><option>JS Bank</option><option>Habib Metropolitan Bank</option><option>Soneri Bank</option><option>Other Pakistani Bank</option></select><label class="section-title">Account holder name</label><input id="wdName" class="field" placeholder="Full account holder name"><label class="section-title">Account number</label><input id="wdAccount" class="field" placeholder="Account number"><label class="section-title">IBAN</label><input id="wdIban" class="field" placeholder="PK...">'}
async function requestWithdrawal(){const amount=Number($('wdAmount').value),method=$('wdMethod').value,account=$('wdAccount').value.trim();if(!(amount>0)||!account)return alert('Enter the amount and account details.');const body={amount,method,account};if(method==='Bank Account'){body.account=JSON.stringify({bankName:$('wdBank').value,accountName:$('wdName').value,accountNumber:account,iban:$('wdIban').value.trim()})}try{const r=await api('/withdrawals',{method:'POST',body:JSON.stringify(body)});$('wdMsg').textContent=r.message;setTimeout(()=>openPage('history'),500)}catch(e){alert(e.message)}}
async function renderProfile(){const p=await api('/profile');$('content').innerHTML=`<div class="page-title"><div><h2>My Profile</h2><div class="muted">Account information</div></div></div><div class="panel"><div class="profile-head"><div class="avatar">${esc(p.username[0].toUpperCase())}</div><div><h3>${esc(p.username)}</h3><small class="muted">Joined ${new Date(p.created_at).toLocaleDateString()}</small></div></div><div class="section-title">Account</div><div class="list-item"><div class="row"><span>Username</span><b>${esc(p.username)}</b></div><div class="row"><span>Referral code</span><b>${esc(p.referral_code)}</b></div><div class="row"><span>Referred by</span><b>${esc(p.referred_by||'None')}</b></div><div class="row"><span>Referral earnings</span><b>${money(p.referral_earnings)}</b></div></div><div class="notice">For security, your password is never displayed. Use the password-change function to update it.</div><button class="outline" onclick="changePassword()">Change password</button></div>`}
async function changePassword(){const current=prompt('Current password');if(current===null)return;const next=prompt('New password (6+ characters)');if(!next)return;try{await api('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword:current,newPassword:next})});alert('Password changed successfully.')}catch(e){alert(e.message)}}
async function renderHistory(){const [d,w]=await Promise.all([api('/payments'),api('/withdrawals')]);const items=[...d.map(x=>({type:'Deposit',amount:x.amount,status:x.status,date:x.created_at,extra:x.transaction_id||'Screenshot submitted'})),...w.map(x=>({type:'Withdrawal',amount:x.amount,status:x.status,date:x.created_at,extra:x.method}))].sort((a,b)=>new Date(b.date)-new Date(a.date));$('content').innerHTML=`<div class="page-title"><div><h2>Account History</h2><div class="muted">Deposits and withdrawals</div></div></div><div class="panel">${items.length?items.map(x=>`<div class="list-item"><div class="row"><b>${x.type}</b><span class="status ${x.status}">${x.status}</span></div><div class="row"><b>${money(x.amount)}</b><small>${esc(x.extra)}</small></div><small class="muted">${new Date(x.date).toLocaleString()}</small></div>`).join(''):'<p class="muted">No transactions yet.</p>'}</div>`}
async function renderNotifications(){$('content').innerHTML=`<div class="page-title"><div><h2>Notifications</h2><div class="muted">Account updates</div></div></div><div class="panel"><div class="list-item"><b>Account security</b><p class="muted">Your password is protected and is never displayed in the member portal.</p></div><div class="list-item"><b>Payment review</b><p class="muted">Payment requests remain pending until reviewed by an authorized administrator.</p></div><div class="list-item"><b>Withdrawal review</b><p class="muted">Withdrawal requests are subject to account checks and administrator approval.</p></div></div>`}
async function copyText(t){try{await navigator.clipboard.writeText(t);alert('Copied')}catch{alert(t)}}
startAppIfToken();function startAppIfToken(){if(token)startApp();else{switchAuth('login');$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}}
